### PR TITLE
Address comments

### PR DESCRIPTION
**Pull request by gassmoeller**
This addresses Wolfgangs comment to the PR. Only things left are to update the test output one more time (I changed one test to make it more useful), and to rebase to the current master.

### CODE REVIEW

**Comment by jdannberg** [comment]
Okay, do you want me to do that, or do you just want to take over the pull request and I'll close mine?

**Comment by gassmoeller** [comment]
I guess you are pretty busy, so I can take over (I will leave you commits intact). Let me know if that is ok with you.

**Comment by jdannberg** [comment]
Sure. You can also squash all of my commits if you want :smiley: 
I was just thinking it might be easier for you to rebase it, because I don't really have the overview about all the things you have changed in the last week and if anything would cause a conflict...

**Comment by gassmoeller** [comment]
There will be a lot of conflicts, since Timo updated all test results, and we updated all test results. Yay!

**Pull request merged**
